# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Epubst < Formula
  desc "Compilateur markdown  epub3, outil en ligne de commande .net"
  homepage "https://github.com/amaurybennett/epubst"
  url "https://api.github.com/repos/amaurybennett/epubst/tarball/v1.0.1"
  sha256 "8e45448bd5496f3c3da9cf4c604f396e03f5ad98a41e75fd8ca5ac2763285282"
  license "MIT"

  on_macos do
  end

  def install
    bin.install "epubst"
  end

  test do
    system "#{bin}/epubst", "--help"
  end
end
